<?php
$titulo='Catalogos'; $modulo='Grupos'; $subtitulo=''; require_once __DIR__.'/../../../includes/auth.php'; require_once __DIR__.'/../../../includes/config.php'; ?>
<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"/><title>Grupos | REFASOFT-V4</title><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="shortcut icon" href="<?= BASE_URL ?>/assets/images/favicon.ico"><link href="<?= BASE_URL ?>/assets/css/bootstrap.min.css" rel="stylesheet"/><link href="<?= BASE_URL ?>/assets/css/icons.min.css" rel="stylesheet"/><link href="<?= BASE_URL ?>/assets/css/app.min.css" rel="stylesheet"/><link href="<?= BASE_URL ?>/assets/css/loader.css" rel="stylesheet"/><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"></head><body><?php include_once __DIR__.'/../../../includes/header.php'; ?><div class="wrapper"><div class="container-fluid"><?php include_once __DIR__.'/../../../includes/breadcrumb.php'; ?>
<div class="card-header" style="border-color:darkgray; border-style:dotted;"><h5>Filtros</h5><div class="row"><div class="col-md-6"><label>Nombre</label><div class="input-group"><input id="FiltroNombre" class="form-control filtrar"><div class="input-group-append clean-filter"><span class="input-group-text"><i class="mdi mdi-close-circle text-danger" onclick="clearField('FiltroNombre')"></i></span></div></div></div></div></div>
<div class="row mt-3"><div class="col-12"><div class="card-box"><div class="d-flex justify-content-between align-items-center mb-2"><h4 class="header-title">Catálogo de Grupos</h4><button id="btnNuevo" class="btn btn-primary"><i class="mdi mdi-plus"></i> Nuevo grupo</button></div><div class="table-responsive"><table class="table table-bordered table-hover table-striped"><thead><tr><th style="width:90px" class="text-center">ID</th><th>Nombre</th><th style="width:110px" class="text-center">Acciones</th></tr></thead><tbody id="tbody"></tbody></table></div><div class="row"><div class="col-md-6"><div id="info" class="dataTables_info"></div></div><div class="col-md-6 d-flex justify-content-end"><ul id="pagination" class="pagination mb-0"></ul></div></div></div></div></div></div></div>
<div class="modal fade" id="modalForm"><div class="modal-dialog modal-md modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 id="tituloModal">Nuevo grupo</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form id="form"><input type="hidden" id="id_grupo"><div class="modal-body"><label>Nombre</label><input id="nombre_grupo" class="form-control" maxlength="120" required></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button><button class="btn btn-primary">Guardar</button></div></form></div></div></div>
<div class="modal fade" id="modalEliminar"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5>Eliminar grupo</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body">¿Eliminar <strong id="delNombre"></strong>?</div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button><button type="button" class="btn btn-danger" id="btnConfirmEliminar">Eliminar</button></div></div></div></div>
<?php include_once __DIR__.'/../../../includes/footer.php'; ?><script src="<?= BASE_URL ?>/assets/js/vendor.min.js"></script><script src="<?= BASE_URL ?>/assets/js/app.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script>const URL_CTRL='<?= BASE_URL ?>/controllers/CatGruposController.php';</script>
<script src="<?= BASE_URL ?>/assets/js/pages/catalogo_simple.js"></script>
<script>initCatalogoSimple({key:'id_grupo',name:'nombre_grupo',title:'grupo',ctrl:URL_CTRL,cols:[r=>r.id_grupo,r=>r.nombre_grupo||'—']});</script>
</body></html>
