<?php $titulo='Catalogos'; $modulo='Régimen Fiscal SAT'; $subtitulo=''; require_once __DIR__.'/../../../includes/auth.php'; require_once __DIR__.'/../../../includes/config.php'; ?>
<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"/><title>Régimen Fiscal SAT | REFASOFT-V4</title><meta name="viewport" content="width=device-width, initial-scale=1.0"><link href="<?= BASE_URL ?>/assets/css/bootstrap.min.css" rel="stylesheet"/><link href="<?= BASE_URL ?>/assets/css/icons.min.css" rel="stylesheet"/><link href="<?= BASE_URL ?>/assets/css/app.min.css" rel="stylesheet"/><link href="<?= BASE_URL ?>/assets/css/loader.css" rel="stylesheet" /><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"><style>.clean-filter{display:none;}.clean-filter .input-group-text{cursor:pointer;}</style></head><body><?php include_once __DIR__.'/../../../includes/header.php'; ?><div class="wrapper"><div class="wrapper-loader fade" id="LoadingImage" style="display: none;">
  <div class="loader">
    <div class="loader__figure"></div>
    <p class="loader__label">Cargando...</p>
  </div>
</div><div class="container-fluid"><?php include_once __DIR__.'/../../../includes/breadcrumb.php'; ?>
<div class="card-header" style="border-color:darkgray; border-style:dotted;"><h5>Filtros</h5><div class="row"><div class="col-lg-12"><div class="row"><div class="col-md-4"><div class="form-group"><label for="FiltroClave">Clave SAT</label><div class="input-group"><input id="FiltroClave" class="form-control filtrar"><div class="input-group-append clean-filter"><span class="input-group-text"><i class="mdi mdi-close-circle text-danger" onclick="clearField('FiltroClave')"></i></span></div></div></div></div><div class="col-md-8"><div class="form-group"><label for="FiltroDescripcion">Descripción</label><div class="input-group"><input id="FiltroDescripcion" class="form-control filtrar"><div class="input-group-append clean-filter"><span class="input-group-text"><i class="mdi mdi-close-circle text-danger" onclick="clearField('FiltroDescripcion')"></i></span></div></div></div></div></div></div></div></div>
<div class="row mt-3"><div class="col-12"><div class="card-box"><div class="d-flex justify-content-between align-items-center mb-2"><h4 class="header-title">Catálogo SAT Régimen Fiscal SAT</h4><button id="btnNuevo" class="btn btn-primary"><i class="mdi mdi-plus"></i> Nuevo régimen</button></div><div id="emptyState" class="alert alert-warning d-none mb-2">No hay registros que coincidan con los filtros.</div><div class="table-responsive"><table class="table table-bordered table-hover table-striped"><thead><tr><th>Clave</th><th>Descripción</th><th>Física</th><th>Moral</th><th>Activo</th><th style="width:110px" class="text-center">Acciones</th></tr></thead><tbody id="tbodyRegistros"></tbody></table></div><div class="row align-items-center justify-content-between mt-2"><div class="col-md-6"><div id="infoRegistros" class="dataTables_info"></div></div><div class="col-md-6 d-flex justify-content-end"><nav><ul id="pagination" class="pagination justify-content-end mb-0"></ul></nav></div></div></div></div></div>
</div></div>
<div class="modal fade" id="modalForm"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 id="tituloModal">Nuevo régimen</h5><button class="close" data-dismiss="modal"><span>&times;</span></button></div><form id="formRegistro"><input type="hidden" id="OriginalClaveRegimenFiscal"><div class="modal-body"><div class="row"><div class="col-md-3"><label>Clave</label><input id="ClaveRegimenFiscal" class="form-control" required maxlength="3"></div><div class="col-md-9"><label>Descripción</label><input id="Descripcion" class="form-control" required></div><div class="col-md-6 mt-2"><label>Aplica Persona Física</label><input id="Fisica" class="form-control"></div><div class="col-md-6 mt-2"><label>Aplica Persona Moral</label><input id="Moral" class="form-control"></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button><button class="btn btn-primary">Guardar</button></div></form></div></div></div>
<div class="modal fade" id="modalEliminar"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5>Desactivar régimen</h5><button class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body">¿Desactivar <strong id="delNombre"></strong>?</div><div class="modal-footer"><button class="btn btn-light" data-dismiss="modal">Cancelar</button><button type="button" id="btnConfirmEliminar" class="btn btn-danger">Desactivar</button></div></div></div></div>
<?php include_once __DIR__.'/../../../includes/footer.php'; ?><script src="<?= BASE_URL ?>/assets/js/vendor.min.js"></script><script src="<?= BASE_URL ?>/assets/js/app.min.js"></script><script src="<?= BASE_URL ?>/assets/js/loader.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script>
$(function(){let paginaActual=1;const limitePorPagina=10;const URL_CTRL='<?= BASE_URL ?>/controllers/CatSatRegimenFiscalController.php'; const e=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');cargarRegistros(1);$(document).on('input','#ClaveRegimenFiscal,#FiltroClave',function(){this.value=this.value.toUpperCase();});
$('.filtrar').change(function(){const $el=$(this);if(($el.is(':checkbox')&&$el.is(':checked'))||($el.val()&&$el.val().length>0))$el.closest('.input-group, .form-group').find('.clean-filter').css({display:'flex'});else $el.closest('.input-group, .form-group').find('.clean-filter').css({display:'none'});$el.blur();setTimeout(()=>cargarRegistros(1),200);}).keypress(function(ev){if(ev.charCode==13)cargarRegistros(1);}).keyup(function(){if($(this).val().length>0)$(this).closest('.input-group, .form-group').find('.clean-filter').css({display:'flex'});else $(this).closest('.input-group, .form-group').find('.clean-filter').css({display:'none'});}); $('.clean-filter').click(function(){const $el=$(this).closest('.input-group, .form-group').find('.filtrar');$el.val('').trigger('change');cargarRegistros(1);});
$('#btnNuevo').click(()=>{$('#formRegistro')[0].reset();$('#OriginalClaveRegimenFiscal').val('');$('#tituloModal').text('Nuevo régimen');$('#modalForm').modal('show');});
$(document).on('click','a.accion-editar',function(ev){ev.preventDefault();$.getJSON(URL_CTRL,{accion:'detalle',ClaveRegimenFiscal:$(this).data('id')},resp=>{const r=resp?.data||{};Object.keys(r).forEach(k=>$('#'+k).val(r[k]??''));$('#tituloModal').text('Editar régimen');$('#modalForm').modal('show');});});
$('#formRegistro').submit(function(ev){ev.preventDefault();const key=$('#OriginalClaveRegimenFiscal').val()||$('#ClaveRegimenFiscal').val();const payload={OriginalClaveRegimenFiscal:key,ClaveRegimenFiscal:$('#ClaveRegimenFiscal').val().trim().toUpperCase(),Descripcion:$('#Descripcion').val().trim(),Fisica:$('#Fisica').val().trim(),Moral:$('#Moral').val().trim()};const accion=$('#OriginalClaveRegimenFiscal').val()?'actualizar':'crear';$.ajax({url:URL_CTRL+'?accion='+accion,method:'POST',data:JSON.stringify(payload),contentType:'application/json; charset=UTF-8',dataType:'json'}).done(r=>{if(r?.ok){$('#modalForm').modal('hide');toastr.success('Régimen Fiscal SAT guardado correctamente.');cargarRegistros(accion==='crear'?1:paginaActual);}else toastr.error(r?.msg||'No se pudo guardar.');}).fail(()=>toastr.error('Error al guardar.'));});
$(document).on('click','a.accion-eliminar',function(ev){ev.preventDefault();$('#btnConfirmEliminar').data('id',$(this).data('id'));$('#delNombre').text($(this).data('nombre'));$('#modalEliminar').modal('show');});$('#btnConfirmEliminar').click(function(){$.post(URL_CTRL,{accion:'eliminar',ClaveRegimenFiscal:$(this).data('id')},r=>{if(r?.ok){$('#modalEliminar').modal('hide');toastr.success('Régimen Fiscal SAT desactivado.');cargarRegistros(paginaActual);}else toastr.error(r?.msg||'No se pudo desactivar.');},'json');});
function cargarRegistros(p){paginaActual=p;$.post(URL_CTRL,{accion:'listar',pagina:p,limite:limitePorPagina,ClaveRegimenFiscal:$('#FiltroClave').val(),descripcion:$('#FiltroDescripcion').val()},function(resp){const rows=resp?.data||[];const total=parseInt(resp?.total||0,10);let t='';if(!rows.length){$('#emptyState').removeClass('d-none');t='<tr><td colspan="6" class="text-center text-muted">— No hay registros —</td></tr>';}else{$('#emptyState').addClass('d-none');rows.forEach(v=>{t+=`<tr><td><b>${e(v.ClaveRegimenFiscal||'')}</b></td><td>${e(v.Descripcion||'—')}</td><td>${e(v.Fisica||'—')}</td><td>${e(v.Moral||'—')}</td><td>${+v.Activo===1?'Sí':'No'}</td><td class="text-center"><div class="btn-group dropdown"><a href="javascript:void(0);" class="table-action-btn dropdown-toggle arrow-none btn btn-light btn-sm" data-toggle="dropdown"><i class="mdi mdi-dots-horizontal"></i></a><div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item accion-editar" href="#" data-id="${e(v.ClaveRegimenFiscal)}"><i class="mdi mdi-square-edit-outline mr-2 text-muted font-18 vertical-middle"></i>Editar</a><a class="dropdown-item accion-eliminar" href="#" data-id="${e(v.ClaveRegimenFiscal)}" data-nombre="${e(v.Descripcion||'')}"><i class="mdi mdi-delete mr-2 text-muted font-18 vertical-middle"></i>Desactivar</a></div></div></td></tr>`;});}$('#tbodyRegistros').html(t);if(total===0)$('#infoRegistros').text('No hay registros para mostrar');else $('#infoRegistros').text(`Mostrando ${(p-1)*limitePorPagina+1} a ${Math.min(p*limitePorPagina,total)} de ${total} registros`);configurarPaginacion(p,total,limitePorPagina);},'json').fail(()=>toastr.error('Error al cargar datos.'));}
function configurarPaginacion(currentPage,totalItems,itemsPerPage=10){const totalPages=Math.max(1,Math.ceil(totalItems/itemsPerPage));const $ul=$('#pagination');const maxVisiblePages=5;$ul.empty();if(totalPages<=1){$ul.closest('nav').hide();return;}else{$ul.closest('nav').show();}let startPage=Math.max(1,currentPage-Math.floor(maxVisiblePages/2));let endPage=Math.min(totalPages,startPage+maxVisiblePages-1);if(endPage-startPage+1<maxVisiblePages)startPage=Math.max(1,endPage-maxVisiblePages+1);if(currentPage>1){$ul.append(`<li class="page-item"><a class="page-link" href="javascript:void(0);" data-page="1">Primera</a></li>`);$ul.append(`<li class="page-item"><a class="page-link" href="javascript:void(0);" data-page="${currentPage-1}">&laquo; Anterior</a></li>`);}for(let i=startPage;i<=endPage;i++){$ul.append(`<li class="page-item ${i===currentPage?'active':''}"><a class="page-link" href="javascript:void(0);" data-page="${i}">${i}</a></li>`);}if(currentPage<totalPages){$ul.append(`<li class="page-item"><a class="page-link" href="javascript:void(0);" data-page="${currentPage+1}">Siguiente &raquo;</a></li>`);$ul.append(`<li class="page-item"><a class="page-link" href="javascript:void(0);" data-page="${totalPages}">Última</a></li>`);} $ul.off('click','a.page-link').on('click','a.page-link',function(ev){ev.preventDefault();const page=Number($(this).data('page'));if(Number.isFinite(page)){paginaActual=page;cargarRegistros(paginaActual);}});} });
function clearField(id){const el=document.getElementById(id);if(!el)return;el.value='';el.dispatchEvent(new Event('change'));}
</script>
<script>
function syncClear(inputEl){
  if(!inputEl) return;
  const $input=$(inputEl);
  const hasValue=($input.val()||'').toString().trim().length>0;
  $input.closest('.input-group, .form-group').find('.clean-filter').css({display:hasValue?'flex':'none'});
}

function clearField(id){
  const el=document.getElementById(id);
  if(!el) return;
  if(el.type==='checkbox'){
    el.checked=false;
  }else{
    el.value='';
  }
  syncClear(el);
  el.dispatchEvent(new Event('input'));
  el.dispatchEvent(new Event('change'));
}

$(function(){
  $('.filtrar').each(function(){ syncClear(this); });
  $(document).on('input change blur', '.filtrar', function(){ syncClear(this); });
  $(document).on('click', '.clean-filter', function(){
    const input=this.closest('.input-group, .form-group')?.querySelector('.filtrar');
    if(input){ setTimeout(function(){ syncClear(input); }, 0); }
  });
});
</script>
</body></html>
