<?php $titulo='Catalogos'; $modulo='Clientes SAT'; $subtitulo=''; require_once __DIR__.'/../../../includes/auth.php'; require_once __DIR__.'/../../../includes/config.php'; ?>
<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"/><title>Clientes SAT | REFASOFT-V4</title><meta name="viewport" content="width=device-width, initial-scale=1.0"><link href="<?= BASE_URL ?>/assets/css/bootstrap.min.css" rel="stylesheet"/><link href="<?= BASE_URL ?>/assets/css/icons.min.css" rel="stylesheet"/><link href="<?= BASE_URL ?>/assets/css/app.min.css" rel="stylesheet"/><link href="<?= BASE_URL ?>/assets/css/loader.css" rel="stylesheet" /><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"><style>.clean-filter{display:none;}.clean-filter .input-group-text{cursor:pointer;}</style></head><body><?php include_once __DIR__.'/../../../includes/header.php'; ?><div class="wrapper"><div class="wrapper-loader fade" id="LoadingImage" style="display: none;">
  <div class="loader">
    <div class="loader__figure"></div>
    <p class="loader__label">Cargando...</p>
  </div>
</div><div class="container-fluid"><?php include_once __DIR__.'/../../../includes/breadcrumb.php'; ?>
<div class="card-header" style="border-color:darkgray; border-style:dotted;"><h5>Filtros</h5><div class="row"><div class="col-lg-12"><div class="row"><div class="col-md-4"><div class="form-group"><label for="FiltroClave">RFC</label><div class="input-group"><input id="FiltroClave" class="form-control filtrar"><div class="input-group-append clean-filter"><span class="input-group-text"><i class="mdi mdi-close-circle text-danger" onclick="clearField('FiltroClave')"></i></span></div></div></div></div><div class="col-md-8"><div class="form-group"><label for="FiltroDescripcion">Razón social</label><div class="input-group"><input id="FiltroDescripcion" class="form-control filtrar"><div class="input-group-append clean-filter"><span class="input-group-text"><i class="mdi mdi-close-circle text-danger" onclick="clearField('FiltroDescripcion')"></i></span></div></div></div></div></div></div></div></div>
<div class="row mt-3"><div class="col-12"><div class="card-box"><div class="d-flex justify-content-between align-items-center mb-2"><h4 class="header-title">Catálogo Clientes SAT</h4><button id="btnNuevo" class="btn btn-primary"><i class="mdi mdi-plus"></i> Nuevo cliente SAT</button></div><div id="emptyState" class="alert alert-warning d-none mb-2">No hay registros que coincidan con los filtros.</div><div class="table-responsive"><table class="table table-bordered table-hover table-striped"><thead><tr><th>ID</th><th>RFC</th><th>Razón social</th><th>Régimen</th><th>Uso CFDI</th><th>CP</th><th style="width:110px">Acciones</th></tr></thead><tbody id="tbodyRegistros"></tbody></table></div><div class="row align-items-center justify-content-between mt-2"><div class="col-md-6"><div id="infoRegistros" class="dataTables_info"></div></div><div class="col-md-6 d-flex justify-content-end"><nav><ul id="pagination" class="pagination justify-content-end mb-0"></ul></nav></div></div></div></div></div>
</div></div>
<div class="modal fade" id="modalForm"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 id="tituloModal">Nuevo cliente SAT</h5><button class="close" data-dismiss="modal"><span>&times;</span></button></div><form id="formRegistro"><input type="hidden" id="row_key"><div class="modal-body"><div class="row"><div class="col-md-2"><label>ID</label><input id="id" type="number" class="form-control"></div><div class="col-md-3"><label>RFC</label><input id="rfc" class="form-control" maxlength="13"></div><div class="col-md-7"><label>Razón social</label><input id="razon_social" class="form-control" maxlength="118"></div><div class="col-md-4 mt-2"><label>Nombre comercial</label><input id="nombre_comercial" class="form-control"></div><div class="col-md-2 mt-2"><label>Régimen</label><input id="regimen_fiscal" class="form-control"></div><div class="col-md-2 mt-2"><label>Uso CFDI</label><input id="uso_cdfi" class="form-control"></div><div class="col-md-2 mt-2"><label>CP</label><input id="dom_fiscal_cp" class="form-control"></div><div class="col-md-2 mt-2"><label>Teléfono</label><input id="telefono" class="form-control"></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button><button class="btn btn-primary">Guardar</button></div></form></div></div></div>
<div class="modal fade" id="modalEliminar"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5>Eliminar cliente SAT</h5><button class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body">Este catálogo no maneja desactivación lógica.</div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button></div></div></div></div>
<?php include_once __DIR__.'/../../../includes/footer.php'; ?><script src="<?= BASE_URL ?>/assets/js/vendor.min.js"></script><script src="<?= BASE_URL ?>/assets/js/app.min.js"></script><script src="<?= BASE_URL ?>/assets/js/loader.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script>
$(function(){let paginaActual=1;const limitePorPagina=10;const URL_CTRL='<?= BASE_URL ?>/controllers/ClientesSatController.php';const e=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');cargarRegistros(1);$(document).on('input','#rfc,#FiltroClave',function(){this.value=this.value.toUpperCase();});
$('.filtrar').change(function(){const $el=$(this);if(($el.val()&&$el.val().length>0))$el.closest('.input-group, .form-group').find('.clean-filter').css({display:'flex'});else $el.closest('.input-group, .form-group').find('.clean-filter').css({display:'none'});$el.blur();setTimeout(()=>cargarRegistros(1),200);}).keypress(function(ev){if(ev.charCode==13)cargarRegistros(1);}).keyup(function(){if($(this).val().length>0)$(this).closest('.input-group, .form-group').find('.clean-filter').css({display:'flex'});else $(this).closest('.input-group, .form-group').find('.clean-filter').css({display:'none'});}); $('.clean-filter').click(function(){const $el=$(this).closest('.input-group, .form-group').find('.filtrar');$el.val('').trigger('change');cargarRegistros(1);});
$('#btnNuevo').click(()=>{$('#formRegistro')[0].reset();$('#row_key').val('');$('#tituloModal').text('Nuevo cliente SAT');$('#modalForm').modal('show');});
$(document).on('click','a.accion-editar',function(ev){ev.preventDefault();$.getJSON(URL_CTRL,{accion:'detalle',id:$(this).data('id'),rfc:$(this).data('rfc'),row_key:$(this).data('row')},resp=>{const r=resp?.data||{};Object.keys(r).forEach(k=>$('#'+k).val(r[k]??''));$('#tituloModal').text('Editar cliente SAT');$('#modalForm').modal('show');});});
$('#formRegistro').submit(function(ev){ev.preventDefault();const payload={};$(this).find('input').each(function(){if(this.id)payload[this.id]=$(this).val();});const accion=payload.row_key?'actualizar':'crear';$.ajax({url:URL_CTRL+'?accion='+accion,method:'POST',data:JSON.stringify(payload),contentType:'application/json; charset=UTF-8',dataType:'json'}).done(r=>{if(r?.ok){$('#modalForm').modal('hide');toastr.success('Cliente SAT guardado correctamente.');cargarRegistros(accion==='crear'?1:paginaActual);}else toastr.error(r?.msg||'No se pudo guardar.');}).fail(()=>toastr.error('Error al guardar.'));});
function cargarRegistros(p){paginaActual=p;$.post(URL_CTRL,{accion:'listar',pagina:p,limite:limitePorPagina,rfc:$('#FiltroClave').val(),razon_social:$('#FiltroDescripcion').val()},function(resp){const rows=resp?.data||[];const total=parseInt(resp?.total||0,10);let t='';if(!rows.length){$('#emptyState').removeClass('d-none');t='<tr><td colspan="7" class="text-center text-muted">— No hay registros —</td></tr>';}else{$('#emptyState').addClass('d-none');rows.forEach(v=>{t+=`<tr><td>${v.id??'—'}</td><td><b>${e(v.rfc||'')}</b></td><td>${e(v.razon_social||'—')}</td><td>${e(v.regimen_fiscal||'—')}</td><td>${e(v.uso_cdfi||'—')}</td><td>${e(v.dom_fiscal_cp||'—')}</td><td class="text-center"><a class="btn btn-light btn-sm accion-editar" href="#" data-id="${v.id??''}" data-rfc="${e(v.rfc||'')}" data-row="${e(v.row_key||'')}"><i class="mdi mdi-square-edit-outline"></i></a></td></tr>`;});}$('#tbodyRegistros').html(t);if(total===0)$('#infoRegistros').text('No hay registros para mostrar');else $('#infoRegistros').text(`Mostrando ${(p-1)*limitePorPagina+1} a ${Math.min(p*limitePorPagina,total)} de ${total} registros`);configurarPaginacion(p,total,limitePorPagina);},'json');}
function configurarPaginacion(currentPage,totalItems,itemsPerPage=10){const totalPages=Math.max(1,Math.ceil(totalItems/itemsPerPage));const $ul=$('#pagination');const maxVisiblePages=5;$ul.empty();if(totalPages<=1){$ul.closest('nav').hide();return;}else{$ul.closest('nav').show();}let startPage=Math.max(1,currentPage-Math.floor(maxVisiblePages/2));let endPage=Math.min(totalPages,startPage+maxVisiblePages-1);if(endPage-startPage+1<maxVisiblePages)startPage=Math.max(1,endPage-maxVisiblePages+1);if(currentPage>1){$ul.append(`<li class="page-item"><a class="page-link" href="javascript:void(0);" data-page="1">Primera</a></li>`);$ul.append(`<li class="page-item"><a class="page-link" href="javascript:void(0);" data-page="${currentPage-1}">&laquo; Anterior</a></li>`);}for(let i=startPage;i<=endPage;i++){$ul.append(`<li class="page-item ${i===currentPage?'active':''}"><a class="page-link" href="javascript:void(0);" data-page="${i}">${i}</a></li>`);}if(currentPage<totalPages){$ul.append(`<li class="page-item"><a class="page-link" href="javascript:void(0);" data-page="${currentPage+1}">Siguiente &raquo;</a></li>`);$ul.append(`<li class="page-item"><a class="page-link" href="javascript:void(0);" data-page="${totalPages}">Última</a></li>`);} $ul.off('click','a.page-link').on('click','a.page-link',function(ev){ev.preventDefault();const page=Number($(this).data('page'));if(Number.isFinite(page)){paginaActual=page;cargarRegistros(paginaActual);}});} });
function clearField(id){const el=document.getElementById(id);if(!el)return;el.value='';el.dispatchEvent(new Event('change'));}
</script>
<script>
function syncClear(inputEl){
  if(!inputEl) return;
  const $input=$(inputEl);
  const hasValue=($input.val()||'').toString().trim().length>0;
  $input.closest('.input-group, .form-group').find('.clean-filter').css({display:hasValue?'flex':'none'});
}

function clearField(id){
  const el=document.getElementById(id);
  if(!el) return;
  if(el.type==='checkbox'){
    el.checked=false;
  }else{
    el.value='';
  }
  syncClear(el);
  el.dispatchEvent(new Event('input'));
  el.dispatchEvent(new Event('change'));
}

$(function(){
  $('.filtrar').each(function(){ syncClear(this); });
  $(document).on('input change blur', '.filtrar', function(){ syncClear(this); });
  $(document).on('click', '.clean-filter', function(){
    const input=this.closest('.input-group, .form-group')?.querySelector('.filtrar');
    if(input){ setTimeout(function(){ syncClear(input); }, 0); }
  });
});
</script>
</body></html>
