<?php
include_once __DIR__ . '/../includes/db.php';
class CatSatMonedaModel {
    private $conn; public function __construct(){ global $pdo; $this->conn=$pdo; }
    public function listar(int $pagina=1,int $limite=10,array $f=[]){ $offset=(max(1,$pagina)-1)*max(1,$limite); $sql="SELECT * FROM cat_sat_moneda WHERE activo=1";$p=[]; if(($q=trim($f['q']??''))!==''){ $sql.=" AND (clave_moneda LIKE :q1 OR descripcion LIKE :q2)";$p[':q1']="%$q%";$p[':q2']="%$q%";} if(($c=trim($f['clave_moneda']??''))!==''){ $sql.=" AND clave_moneda LIKE :c";$p[':c']="%".strtoupper($c)."%";} if(($d=trim($f['descripcion']??''))!==''){ $sql.=" AND descripcion LIKE :d";$p[':d']="%$d%";} $sql.=" ORDER BY clave_moneda ASC LIMIT $limite OFFSET $offset"; $st=$this->conn->prepare($sql); foreach($p as $k=>$v){$st->bindValue($k,$v);} $st->execute(); return $st->fetchAll(PDO::FETCH_ASSOC);} 
    public function contar(array $f=[]){ $sql="SELECT COUNT(*) total FROM cat_sat_moneda WHERE activo=1";$p=[]; if(($q=trim($f['q']??''))!==''){ $sql.=" AND (clave_moneda LIKE :q1 OR descripcion LIKE :q2)";$p[':q1']="%$q%";$p[':q2']="%$q%";} if(($c=trim($f['clave_moneda']??''))!==''){ $sql.=" AND clave_moneda LIKE :c";$p[':c']="%".strtoupper($c)."%";} if(($d=trim($f['descripcion']??''))!==''){ $sql.=" AND descripcion LIKE :d";$p[':d']="%$d%";} $st=$this->conn->prepare($sql); foreach($p as $k=>$v){$st->bindValue($k,$v);} $st->execute(); return (int)($st->fetch(PDO::FETCH_ASSOC)['total']??0);} 
    public function obtenerPorId(int $id){ $st=$this->conn->prepare("SELECT * FROM cat_sat_moneda WHERE id_moneda=:id LIMIT 1"); $st->execute([':id'=>$id]); return $st->fetch(PDO::FETCH_ASSOC);} 
    public function crear(array $d){ $st=$this->conn->prepare("INSERT INTO cat_sat_moneda(clave_moneda,descripcion,decimales,activo,fecha_creacion) VALUES(:c,:d,:m,1,NOW())"); $ok=$st->execute([':c'=>strtoupper(trim($d['clave_moneda']??'')),':d'=>trim($d['descripcion']??''),':m'=>(int)($d['decimales'] ?? 2)]); return $ok?(int)$this->conn->lastInsertId():0;} 
    public function actualizar(int $id,array $d){ $st=$this->conn->prepare("UPDATE cat_sat_moneda SET clave_moneda=:c, descripcion=:d, decimales=:m WHERE id_moneda=:id"); return $st->execute([':c'=>strtoupper(trim($d['clave_moneda']??'')),':d'=>trim($d['descripcion']??''),':m'=>(int)($d['decimales'] ?? 2),':id'=>$id]); }
    public function eliminar(int $id){ return $this->conn->prepare("UPDATE cat_sat_moneda SET activo=0 WHERE id_moneda=:id")->execute([':id'=>$id]); }
    public function listarMin(string $q='',int $lim=50){ $sql="SELECT id_moneda, clave_moneda, descripcion, decimales FROM cat_sat_moneda WHERE activo=1";$p=[]; if($q!==''){ $sql.=" AND (clave_moneda LIKE :q1 OR descripcion LIKE :q2)";$p[':q1']="%$q%";$p[':q2']="%$q%";} $sql.=" ORDER BY clave_moneda ASC LIMIT :l"; $st=$this->conn->prepare($sql); foreach($p as $k=>$v){$st->bindValue($k,$v);} $st->bindValue(':l',$lim,PDO::PARAM_INT); $st->execute(); return $st->fetchAll(PDO::FETCH_ASSOC);} }
