<?php
include_once __DIR__ . '/../includes/db.php';
class ClientesSatModel {
    private $conn; public function __construct(){ global $pdo; $this->conn=$pdo; }
    public function listar(int $pagina=1,int $limite=10,array $f=[]){ $offset=(max(1,$pagina)-1)*max(1,$limite); $sql="SELECT * FROM clientes_sat WHERE activo=1"; $p=[]; if(($q=trim($f['q']??''))!==''){ $sql.=" AND (rfc LIKE :q1 OR razon_social LIKE :q2 OR codigo_postal LIKE :q3)"; $p[':q1']="%$q%";$p[':q2']="%$q%";$p[':q3']="%$q%"; } if(($r=trim($f['rfc']??''))!==''){ $sql.=" AND rfc LIKE :r"; $p[':r']="%".strtoupper($r)."%"; } if(($rs=trim($f['razon_social']??''))!==''){ $sql.=" AND razon_social LIKE :rs"; $p[':rs']="%$rs%"; } if(($cp=trim($f['codigo_postal']??''))!==''){ $sql.=" AND codigo_postal LIKE :cp"; $p[':cp']="%$cp%"; } $sql.=" ORDER BY id_cliente_sat ASC LIMIT $limite OFFSET $offset"; $st=$this->conn->prepare($sql); foreach($p as $k=>$v){$st->bindValue($k,$v);} $st->execute(); return $st->fetchAll(PDO::FETCH_ASSOC);} 
    public function contar(array $f=[]){ $sql="SELECT COUNT(*) total FROM clientes_sat WHERE activo=1"; $p=[]; if(($q=trim($f['q']??''))!==''){ $sql.=" AND (rfc LIKE :q1 OR razon_social LIKE :q2 OR codigo_postal LIKE :q3)"; $p[':q1']="%$q%";$p[':q2']="%$q%";$p[':q3']="%$q%"; } if(($r=trim($f['rfc']??''))!==''){ $sql.=" AND rfc LIKE :r"; $p[':r']="%".strtoupper($r)."%"; } if(($rs=trim($f['razon_social']??''))!==''){ $sql.=" AND razon_social LIKE :rs"; $p[':rs']="%$rs%"; } if(($cp=trim($f['codigo_postal']??''))!==''){ $sql.=" AND codigo_postal LIKE :cp"; $p[':cp']="%$cp%"; } $st=$this->conn->prepare($sql); foreach($p as $k=>$v){$st->bindValue($k,$v);} $st->execute(); return (int)($st->fetch(PDO::FETCH_ASSOC)['total']??0);} 
    public function obtenerPorId(int $id){ $st=$this->conn->prepare("SELECT * FROM clientes_sat WHERE id_cliente_sat=:id LIMIT 1"); $st->execute([':id'=>$id]); return $st->fetch(PDO::FETCH_ASSOC);} 
    public function crear(array $d){ $st=$this->conn->prepare("INSERT INTO clientes_sat(rfc,razon_social,id_regimen_fiscal,id_uso_cfdi,codigo_postal,activo,fecha_creacion) VALUES(:r,:n,:reg,:uso,:cp,1,NOW())"); $ok=$st->execute([':r'=>strtoupper(trim($d['rfc']??'')),':n'=>trim($d['razon_social'] ?? $d['nombre'] ?? ''),':reg'=>($d['id_regimen_fiscal']??null)?:null,':uso'=>($d['id_uso_cfdi']??null)?:null,':cp'=>trim($d['codigo_postal']??'')]); return $ok?(int)$this->conn->lastInsertId():0;} 
    public function actualizar(int $id,array $d){ $st=$this->conn->prepare("UPDATE clientes_sat SET rfc=:r, razon_social=:n, id_regimen_fiscal=:reg, id_uso_cfdi=:uso, codigo_postal=:cp WHERE id_cliente_sat=:id"); return $st->execute([':r'=>strtoupper(trim($d['rfc']??'')),':n'=>trim($d['razon_social'] ?? $d['nombre'] ?? ''),':reg'=>($d['id_regimen_fiscal']??null)?:null,':uso'=>($d['id_uso_cfdi']??null)?:null,':cp'=>trim($d['codigo_postal']??''),':id'=>$id]); }
    public function eliminar(int $id){ return $this->conn->prepare("UPDATE clientes_sat SET activo=0 WHERE id_cliente_sat=:id")->execute([':id'=>$id]); }
}
